---
- name: create docker network
  command: "docker network create cryptowatch"
  become: yes

- name: start zipkin
  command: "{{ dest_folder }}/sink/startZipkin.sh"
  become: yes

- name: start kafka
  command: "{{ dest_folder }}/sink/startKafka.sh"
  become: yes

- name: add kafka host entry
  lineinfile:
    path: "/etc/hosts"
    regexp: '127\.0\.0\.1       localhost'
    insertafter: '127.0.0.1       localhost'
    line: '127.0.0.1       kafka'
  become: yes

- name: start keycloak
  command: "{{ dest_folder }}/sink/startKeycloak.sh"
  become: yes

- name: create sink artefact
  command: "mvn -s {{ dest_folder }}/sink/settings.xml -f {{ dest_folder }}/sink/pom.xml clean install"

- name: run npm install
  command: "npm install {{ dest_folder }}/cockpit"

- name: move node_modules
  shell: "mv node_modules {{ dest_folder }}/cockpit/"

- name: create cockpit artefact
  command: "{{ dest_folder }}/cockpit/start.sh"

- name: install nightwatch for UI tests
  shell: "npm install nightwatch -g"
